flag.flag.*:
  type: config_entity
  label: 'Flag'
  mapping:
    id:
      type: string
      label: 'Flag identifier'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Name'
    types:
      type: sequence
      label: 'The entity subtypes this flag applies to'
      sequence:
        - type: string
    entity_type:
      type: string
      label: 'Flaggable entity type'
    enabled:
      type: boolean
      label: 'Whether the flag is enabled'
    global:
      type: boolean
      label: 'Whether the flag is global'
    flag_short:
      type: string
      label: 'Flag link text'
    flag_long:
      type: string
      label: 'Flag link description text'
    flag_message:
      type: string
      label: 'Flag message'
    unflag_short:
      type: string
      label: 'Unflag link text'
    unflag_long:
      type: string
      label: 'Unflag link description text'
    unflag_message:
      type: string
      label: 'Unflag message'
    unflag_denied_text:
      type: string
      label: 'Unflag denied text'
    weight:
      type: integer
      label: 'Weight'
    flag_type:
      type: string
      label: 'ID of the Flag Type plugin'
    link_type:
      type: string
      label: 'ID of the Link Type plugin'
